---
# tasks file for docker swarm nodes
- name: install essential stuff
  become: yes
  yum:  name={{ item }}
        state=latest
  with_items:
    - wget
    - awscli
  tags:
    - worker

- name: create directory for crontab scripts
  become: yes
  file:
   path: "{{ cron_scripts }}"
   state: directory
   owner: root
   group: root
   mode: 0755
  tags:
    - worker

- name: add script to terminate instance if required
  become: yes
  copy:
    src: instance_terminate.sh
    dest: "{{ cron_scripts }}/instance_terminate.sh"
    owner: root
    group: root
    mode: 0755
  tags:
    - worker

- name: copy shell script to /etc/profile.d te set environment variable
  template: src=terminate_limits.sh.j2 dest=/etc/profile.d/terminate_limits.sh force=yes
  become: yes
  tags:
    - worker

- name: add crontab to run reboot script every hour
  become: yes
  cron:
    name: 'check if reboot is required'
    minute: "0"
    hour: "*"
    job: "{{ cron_scripts }}/instance_terminate.sh"
    state: present
  tags:
    - worker

- name: create directory for aws credentials
  become: yes
  file:
    path: /root/.aws
    state: directory
    mode: 0400
  tags:
    - worker

- name: copy aws configuration
  template:
    src: aws_config.j2
    dest: /root/.aws/config
    force: yes
    mode: 0400
  become: yes
  tags:
    - worker

- name: copy aws credentials
  template:
    src: aws_credentials.j2
    dest: /root/.aws/credentials
    force: yes
    mode: 0400
  become: yes
  tags:
    - worker



