---
# tasks file for postgresql
# no reason (yet) to upgrade to later versions of postgres/postgis

- name: install postgresql
  become: yes
  yum:  name={{ item }}
        state=present
  with_items:
        - postgresql-server
        - postgresql-devel
        - postgresql-contrib
        - python-psycopg2
  tags:
    - install

# Filters error message on repeated provision runs
- name: initialize postgresql db
  become: yes
  command: postgresql-setup initdb
  notify: restart postgresql
  register: psql_result
  args:
    creates: /var/lib/pgsql/initdb.log
  failed_when: >
    psql_result.rc != 0 and ("not empty" not in psql_result.stdout)
  changed_when: "psql_result.rc == 0"
  tags:
    - service

- name: Install custom pg_hba config
  become: yes
  become_user: postgres
  template: src=../templates/pg_hba.conf.j2 dest=/var/lib/pgsql/data/pg_hba.conf owner=postgres group=postgres mode=0600

#- name: postgres boots automatically
#  become: yes
#  become_method: sudo
#  command: chkconfig postgresql on
#  tags:
#    - service

- name: make sure postgres is started
  become: yes
  service:  name=postgresql
            state=restarted
            enabled=yes
  tags:
    - service

# The following part should open up postgresql to the ip on which django will run



# This part should go to configuring_postgresql_django.yml
# in order to keep things modular. In this way an uninstall script can mirror
# the above configuration and another database configuration is easily included.

- name: create django db
  become: yes
  become_user: postgres
  postgresql_db: name=djangodb
  tags:
    - configuration

- name: add django user
  become: yes
  become_user: postgres
  postgresql_user:  db=djangodb
                    name=django
                    password="{{ lookup('password', '/tmp/djangopass') }}"
  tags:
    - configuration


- name: grant ALL privs to django user on djangodb
  become: yes
  become_user: postgres
  postgresql_privs: database=djangodb
                    state=present
                    privs=ALL
                    type=database
                    objs=djangodb
                    roles=django
                    grant_option=yes
  tags:
    - configuration
