---
# tasks file for postgresql
# no reason (yet) to upgrade to later versions of postgres/postgis

- name: install postgresql
  become: yes
  become_method: sudo
  yum:  name={{ item }}
        state=present
  with_items:
        - postgresql-server
        - postgresql-devel
        - postgresql-contrib
        - python-psycopg2

# Filters error message on repeated provision runs
- name: initialize postgresql db
  become: yes
  become_method: sudo
  command: postgresql-setup initdb
  notify: restart postgresql
  register: psql_result
  failed_when: >
    psql_result.rc != 0 and ("not empty" not in psql_result.stdout)
  changed_when: "psql_result.rc == 0"

- name: postgres boots automatically
  become: yes
  become_method: sudo
  command: chkconfig postgresql on

- name: make sure postgres is started
  become: yes
  become_method: sudo
  service:  name=postgresql
            state=started
            enabled=yes

# This part should go to configuring_postgresql_django.yml
# in order to keep things modular. In this way an uninstall script can mirror
# the above configuration and another database configuration is easily included.

- name: create django db
  become: yes
  become_method: sudo
  become_user: postgres
  postgresql_db: name=djangodb

- name: add django user
  become_method: sudo
  become_user: postgres
  postgresql_user:
    db=djangodb
    name=django
    password="{{ lookup('password', '/tmp/djangopass') }}"

- name: grant ALL privs to django user on djangodb
  become_method: sudo
  become_user: postgres
  postgresql_privs:
    database=djangodb
    state=present
    privs=ALL
    type=database
    objs=djangodb
    roles=django
    grant_option=yes