---
# tasks file for postgresql
# no reason (yet) to upgrade to later versions of postgres/postgis

- name: install postgresql
  become: yes
  become_method: sudo
  yum:  name={{ item }}
        state=present
  with_items:
        - postgresql-server
        - postgresql-devel
        - postgresql-contrib

- name: initialize postgresql db
  become: yes
  become_method: sudo
  command: service postgresql initdb
  notify: restart postgresql
  ignore_errors: yes  # on multiple revisions, data dir is not empty

- name: postgres boots automatically
  become: yes
  become_method: sudo
  command: chkconfig postgresql on

- name: make sure postgres is started
  become: yes
  become_method: sudo
  service:  name=postgresql
            state=started
            enabled=yes

# This part should go to configuring_postgresql_django.yml
# in order to keep things modular. In this way an uninstall script can mirror
# the above configuration and another database configuration is easily included.

- name: create django db
  postgresql_db: name=django

- name: add django user
  postgresql_user:
    db=django
    name=django
    priv=ALL:ALL