---
# tasks file for nginx
  - name: install nginx
    become: yes
    yum:  name={{ item }}
          state=latest
    with_items:
      - nginx
    tags:
      - install

  - name: create nginx pretty_index directory
    file: path=/opt/delft3d-gt/static/pretty_index/ state=directory recurse=yes
    become: yes
    tags:
      - install

  - name: copy pretty index nginx-before.txt
    copy: src=nginx-before.txt dest=/opt/delft3d-gt/static/pretty_index/nginx-before.txt force=yes
    become: yes
    become_method: sudo
    tags:
      - install

  - name: copy pretty index nginx-after.txt
    copy: src=nginx-after.txt dest=/opt/delft3d-gt/static/pretty_index/nginx-after.txt force=yes
    become: yes
    become_method: sudo
    tags:
      - install

  - name: copy crt
    copy: src=server.crt dest=/etc/pki/nginx/delft3dgt-local.crt force=yes
    become: yes
    become_method: sudo
    tags:
      - install

  - name: create nginx pki directory
    file: path=/etc/pki/nginx/ state=directory recurse=yes
    become: yes
    tags:
      - install

  - name: copy crt
    copy: src=server.crt dest=/etc/pki/nginx/delft3dgt-local.crt force=yes
    become: yes
    become_method: sudo
    tags:
      - install

  - name: create private nginx pki directory
    file: path=/etc/pki/nginx/private state=directory recurse=yes
    become: yes
    tags:
      - install

  - name: copy key
    copy: src=server.key dest=/etc/pki/nginx/private/delft3dgt-local.key force=yes
    become: yes
    become_method: sudo
    tags:
      - install

  - name: set httpd on port 8000
    become: yes
    replace:
      dest: /etc/httpd/conf/httpd.conf
      regexp: '^Listen \d+$'
      replace: 'Listen 8000'
      backup: yes
    notify:
      - restart httpd

  - name: install custom nginx configuration
    become: yes
    template: src=../templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
              mode=0644
    notify:
      - restart nginx
    tags:
      - install

  - name: make sure nginx is started on boot
    become: yes
    service:  name=nginx
              state=started
              enabled=yes
    tags:
      - service
