---
# Global configuration
- name: apply common configuration to all nodes
  hosts: all
  gather_facts: no


  roles:
    - common
    - postgresql
    - apache
    - redis
    - django
    - django_app
    - subversion
    - docker
    - worker_delft3d
    - thredds

