---
# Global configuration
- name: apply common configuration to all nodes
  hosts: all
  become: yes
  become_method: sudo

  roles:
    - common

# Specific for the required components
- include: delft3dgt-django.yml
- include: delft3dgt-postgresql.yml