---
# Global configuration
- name: apply common configuration to all nodes
  hosts: delft3dgt-test
  gather_facts: no

  pre_tasks:
    - name: remove everything in data folder
      become: yes
      shell: 'rm -rf /data/*'
      tags: 'app'

# most basic roles should be further down due to uninstallation
  roles:
    - { role: django_app, tags: 'app'}
    - { role: worker_delft3d, tags: 'simcontainer'}
    - { role: worker_python2.7, tags: 'proccontainer'}
    - { role: worker_dummy, tags: 'dumcontainer'}
    - { role: svn_server, tags: 'repos'}
    - { role: thredds, tags: 'thredds'}