---
# Global configuration
- name: apply common configuration to all nodes
  hosts: all
  gather_facts: no


  roles:
#    - common
#    - postgresql
#    - django
#    - redis
#    - tomcat
#    - subversion
#    - docker
#    - worker_delft3d
    - nodejs

