---
# tasks file for nodejs

- name: run bower uninstall
  command: bower uninstall
  args:
    chdir: "{{ frontend }}"

- name: run npm uninstall
  command: npm uninstall
  args:
    chdir: "{{ frontend }}"

- name: remove gulp, bower and latest version of npm globally
  npm: name={{ item }}
       state=absent
       global=yes
  with_items:
       - npm
       - bower
       - gulp
       - eslint
       - mocha

- name: remove nodejs
  become: yes
  yum: name={{ item }}
       state=absent
  with_items:
       - nodejs
       - npm

- name: delete nmp config file
  file: dest=/home/{{ ansible_ssh_user }}/.npmrc
        state=absent

- name: delete directory frontend
  file: dest={{ frontend }}
        state=absent


