---
# tasks file for common

- name: install aws client
  become: yes
  become_user: django
  pip:  name=awscli
        version=1.10.62
        chdir={{ django_path }}
        extra_args=--upgrade
        virtualenv={{ django_virtualenv }}

- name: install crontab to sync with s3 bucket
  become: yes
  become_user: django
  cron: name='sync with s3 bucket'
        minute=*/5
        job="source {{ django_virtualenv }}/bin/activate; aws s3 sync s3://delft3d-gt/data/container/files /data/container/files"
        state=present

- name: create directory for aws credentials
  become: yes
  become_user: django
  file: path=/home/django/.aws
        state=directory
        mode=0775

- name: copy aws configuration
  template: src=aws_config.j2 dest=/home/django/.aws/config force=yes
  become: yes
  become_user: django

- name: copy aws credentials
  template: src=aws_credentials.j2 dest=/home/django/.aws/credentials force=yes
  become: yes
  become_user: django

- name: disable celery service
  become: yes
  service:  name=celery
            state=stopped
            enabled=no

- name: disable redis service
  become: yes
  service:  name=redis
            state=stopped
            enabled=no
