---
# tasks file for thredds

- name: add paramaters to tomcat configuration
  lineinfile: dest=/etc/tomcat/tomcat.conf line=JAVA_OPTS="-Dtds.content.root.path=/var/lib/tomcat/webapps"
  become: yes
  tags:
    - configuration

# Download thredds 4.6.6 over https
- name: download and install thredds
  get_url: url=https://artifacts.unidata.ucar.edu/content/repositories/unidata-releases/edu/ucar/tds/4.6.6/tds-4.6.6.war
           dest=/usr/share/tomcat/webapps/thredds.war owner=tomcat timeout=300
  become: yes
  notify: restart tomcat
  tags:
    - install

# Check MD5 hash at: Otherwise we should fail this task
# ftp://ftp.unidata.ucar.edu/pub/thredds/4.6/4.6.6/thredds.war.md5
#- name: check md5 of thredds.war

- name: make sure tomcat is started
  become: yes
  service:  name=tomcat
            state=started
            enabled=yes
  tags:
    - service

- name: wait until thredds.war is unpacked in webapps dir
  wait_for: path=/var/lib/tomcat/webapps/thredds/catalog.xml
  tags:
    - install

- name: copy thredds catalog
  become: yes
  template: src=catalog.xml.j2
            dest=/var/lib/tomcat/webapps/thredds/catalog.xml
  notify: restart tomcat
  tags:
    - configuration

- name: copy thredds threddsConfig
  become: yes
  template: src=threddsConfig_deltares.xml.j2
            dest=/var/lib/tomcat/webapps/thredds/threddsConfig.xml
  notify: restart tomcat
  tags:
    - configuration

- name: copy logo
  become: yes
  copy: src={{ hostInstitution_logoUrl }}
        dest=/var/lib/tomcat/webapps/thredds/{{ hostInstitution_logoUrl }}
  notify: restart tomcat
  tags:
    - configuration
