---
# tasks file for celery
- name: create pid folder via /usr/lib/tmpfiles.d
  lineinfile: line="d /var/run/celery 0755 docker docker -"
              state=present
              create=yes
              dest=/etc/tmpfiles.d/celery.conf
  become: yes
  tags:
    - configuration
    - cloud

- name: create pid folder
  become: yes
  file:  path=/var/run/celery
         state=directory
         mode=0755
         owner=docker
         group=docker
  tags:
    - install
    - cloud

- name: create log folder
  become: yes
  file:  path=/var/log/celery
         state=directory
         mode=0755
         owner=docker
         group=docker
  tags:
    - install
    - cloud

- name: copy celeryd configuration file
  become: yes
  template: src=celery.service.j2 dest=/etc/systemd/system/celery.service
  tags:
    - configuration
    - cloud

- name: copy celeryd file
  become: yes
  template: src=celeryd.sysconfig.j2 dest=/etc/sysconfig/celery
  tags:
    - install
    - cloud

- name: reload deamon
  become: yes
  shell: systemctl daemon-reload
  tags:
    - cloud