---
# tasks file for django_app

- name: Add django to redis group
  become: yes
  user: state=present
        name={{ app_user }}
        groups={{ redis_user }}
        append=yes

# [START Commented delft3d-gt-server folder sync]
# - name: add django project folder
#   become: yes
#   file: path={{ django_path }}
#         state=directory
#         mode=0755
#         owner=django
#         group=django
# [END Commented delft3d-gt-server folder sync]

- name: add django static folder
  become: yes
  file: path={{ django_static }}
        state=directory
        mode=0755
        owner=django
        group=django

# activate virtualenv
#- name: virtualenv activate
#  command: source {{ django_virtualenv }}/bin/activate

# [START Commented delft3d-gt-server folder sync]
# Either we init new django project
# - name: Init django project
#   become: yes
#   become_user: django
#   shell: "source {{ django_virtualenv }}/bin/activate; django-admin startproject {{ django_app }} {{ django_path }}"
#   ignore_errors: yes


# Or we get one from git
# - name: Setup the django git
#   become: yes
#   become_user: django
#   git: repo={{ django_git }}
#        version="{{ git_branch }}"
#        dest={{ django_path }}
#        accept_hostkey=yes
#   tags: git
#   ignore_errors: yes
# [END Commented delft3d-gt-server folder sync]


# Newer is
#./manage.py makemigrations
#./manage.py migrate
#./manage.py collectstatic
#- name: Run the Django syncdb command
#  become: yes
#  become_user: django
#  django_manage:
#    command: syncdb
#    app_path: "{{ django_path }}"
#    virtualenv: "{{ django_virtualenv }}"
#    settings: "{{ django_settings_file }}"
#  environment: django_environment
#  when: run_django_syncdb is defined and run_django_syncdb
#  tags: django.syncdb

#- name: Run Django database migrations
#  become: yes
#  become_user: django
#  django_manage:
#    command: migrate
#    app_path: "{{ django_path }}"
#    virtualenv: "{{ django_virtualenv }}"
#    settings: "{{ django_settings_file }}"
#  environment: django_environment
#  when: run_django_db_migrations is defined and run_django_db_migrations
#  tags: django.migrate

# Either way, we can now start django

# STATIC_ROOT = os.path.join(BASE_DIR, "static/")

- name: Install custom settings.py to project
  become: yes
  become_user: django
  template: src=../templates/settings.py.j2 dest={{ django_path }}/{{ django_app }}/settings.py 
# [START Commented delft3d-gt-server folder sync]
  # owner=django group=django mode=0664
# [END Commented delft3d-gt-server folder sync]

- name: Generate static dir
  become: yes
  become_user: django
  shell: "source {{ django_virtualenv }}/bin/activate; python manage.py collectstatic --noinput chdir={{ django_path }}"

# WSGI runs the server, manual startup not needed
#- name: Start django server
#  become: yes
#  become_user: django
#  shell: "source {{ django_virtualenv }}/bin/activate; python manage.py runserver chdir={{ django_path }}"

