---
# tasks file for worker_delft3d

  - name: create docker directory
    file: path=/data/container state=directory

  - name: copy Dockerfile
    copy: src=Dockerfile dest=/data/container

  - name: copy delft3d rpm
    copy: src={{ delft3d_rpm }} dest=/data/container

  - name: start docker
    service: name=docker state=started

  - name: build delft3d docker image
    command: docker build -t delft3d /data/container

  - name: Copy testrun Delft3d
    copy: src={{ test_calculation_local }} dest={{ test_calculation_host}} owner=docker group=docker mode=0744


# docker run -v /data/container/01_standard:/data delft3d