---
# tasks file for django
- name: install pip
  become: yes
  become_method: sudo
  yum:  name={{ item }}
        state=latest
  with_items:
    - python-pip
    - python-devel
    - postgresql-devel
    - gcc
    - make
    - git
  tags:
    - install

- name: upgrade pip
  become: yes
  pip:  name={{ item }}
        extra_args=--upgrade
  with_items:
    - virtualenv
    - pip
  tags:
    - install

- name: add django user
  become: yes
  user: name=django
        state=present
        shell=/bin/bash
  tags:
    - user

- name: Register user id
  become: yes
  become_user: django
  shell: id -u
  register: django_id

- name: add virtualenv folder
  become: yes
  file: path={{ django_virtualenv }}
        state=directory
        mode=0755
        owner=django
        group=django
  tags:
    - install

- name: Add apache to django group
  become: yes
  user: name=httpd
        groups=django
        append=yes
  tags:
    - user

- name: Install wsgi configuration into apache
  become: yes
  template: src=../templates/02_django.j2 dest=/etc/httpd/conf.d/02_django.conf owner=apache group=apache mode=0644
  tags:
    - install

- name: Download apaxy (apache styling)
  becomes: yes
  get_url: url=https://github.com/AdamWhitcroft/Apaxy/archive/master.zip
           dest=/tmp/apaxy.zip
           mode=0440
  ignore_errors: yes

# In ansible v2.0 we can actually put a link here (skip above step)
- name: Unpack apaxy.zip
  becomes: yes
  unarchive:  src=/tmp/apaxy.zip 
              dest=/tmp/apaxy
              copy=no
  ignore_errors: yes

# Results folder is not created here (but in workers, needs to be fixed in sprint4)
- name: Move apaxy styling
  becomes: yes
  command:  mv /tmp/apaxy/apaxy/theme {{ results_folder }}/theme
  ignore_errors: yes

- name: Rename htaccess
  becomes: yes
  command:  mv {{ results_folder }}/theme/htaccess.txt {{ results_folder }}/theme/.htaccess
  ignore_errors: yes

- name: Set correct settings
  become: yes
  template: src=../templates/htacces.j2
            dest={{ results_folder }}/.htaccess
            owner=apache
            group=apache
            mode=0644


