---
# tasks file for ssl

- name: install ssl packages
  become: yes
  yum:  name={{ item }}
        state=latest
  with_items:
    - mod_ssl  # apache module
    - openssl
  tags:
    - package

# It is assumed that on acceptation (or production)
# the server key and cert are placed in the files
# directory of the ssl role
- name: Copy certificate
  become: yes
  copy: src=delft3d.crt dest=/etc/pki/tls/certs
  when: "'delft3dgt-accp' in group_names"
  tags:
    - configuration

- name: Copy certificate key
  become: yes
  copy: src=delft3d.key dest=/etc/pki/tls/private/delft3d.key
  when: "'delft3dgt-accp' in group_names"
  tags:
    - configuration

# In other enviroments (developement and testing)
# a self signed key is generated and used
- name: Set custom options for certifacte request
  become: yes
  template: src=../templates/csr_options.j2
            dest=/root/csr_options.ini
            mode=0664
  when: ("'delft3dgt-test' in group_names") or ("'delft3dgt-local' in group_names") or ("'delft3dgt-dev' in group_names")
  tags:
    - configuration

- name: generate certificate
  become: yes
  command: chdir=/root/ {{ item }}
  with_items:
    - openssl genrsa -out delft3d.key 2048
    - openssl req -new -key delft3d.key -out delft3d.csr -config csr_options.ini
    - openssl x509 -req -days 365 -in delft3d.csr -signkey delft3d.key -out delft3d.crt
  when: ("'delft3dgt-test' in group_names") or ("'delft3dgt-local' in group_names") or ("'delft3dgt-dev' in group_names")
  tags:
    - configuration

- name: copy certificate
  become: yes
  command: chdir=/root/ {{ item }}
  with_items:
    - cp delft3d.crt /etc/pki/tls/certs
    - cp delft3d.key /etc/pki/tls/private/delft3d.key
    - cp delft3d.csr /etc/pki/tls/private/delft3d.csr
  tags:
    - configuration
