---
# tasks file for tomcat7

- name: install tomcat
  yum: name={{ item }}
  with_items:
        - tomcat
        - tomcat-webapps
        - tomcat-admin-webapps  # is admin required?
  become: yes
  become_method: sudo
  notify: start tomcat

