---
# tasks file for common
# system role in datalab
  - name: install epel repository
    yum: name=epel-release state=latest

  - name: upgrade local enviroment
    yum:  name=*
          update_cache=yes
          state=latest

  - name: Set timezone to Amsterdam
    file: src=/usr/share/zoneinfo/Europe/Amsterdam dest=/etc/localtime state=link force=yes

  - name: add delft3dgt user
    user: name={{ delft3duser }}
          state=present
