---
# tasks file for common
  - name: install epel repository
    yum: name=epel-release state=latest

  - name: Set timezone to Amsterdam
    sudo: yes
    file: src=/usr/share/zoneinfo/Europe/Amsterdam dest=/etc/localtime state=link force=yes

  - name: add ansible user
    user: name=ansible
          state=present
