---
# tasks file to install version control system
- name: install mod_dav_svn
  become: yes
  yum: name=mod_dav_svn state=present

- name: configure apache subversion module
  become: yes
  template: src=01_subversion.j2 dest=/etc/httpd/conf.d/01_subversion.conf owner=apache group=apache
  notify: restart httpd

- name: configure subversion directory dir
  become: yes
  file: path={{ svn_path }} state=directory recurse=yes

- name: create repo
  become: yes
  command: /usr/bin/svnadmin create {{svn_path}}/repos chdir={{svn_path}} creates={{svn_path}}/repos/README.txt
  notify: restart httpd

- name: set svn repository permissions
  sudo: yes
  file: path={{ svn_path }}/repos owner=apache group=apache recurse=yes state=directory setype=httpd_sys_content_t