---
# tasks file for worker_delft3d

  - name: create docker directory
    file: path=/data/container state=directory recurse=yes owner=docker
    become: yes

  - name: copy Dockerfile
    copy: src=Dockerfile dest=/data/container
    become: yes
    become_method: sudo
    become_user: docker

  - name: start docker
    service: name=docker state=started
    become: yes
    become_method: sudo

  - name: build python docker image
    command: docker build --no-cache -t python_container /data/container
    become: yes
    become_method: sudo

  - name: create docker workers directory
    file: path=/data/container/files state=directory recurse=yes owner=django group=django mode=0775
    become: yes
    become_method: sudo



# Use the following command to start the container in the provisioned machine:
# docker run python_container