---
# tasks file for roles/ec2
- ec2:
    key_name: deltares
    instance_type: t2.small
    image: ami-7abd0209
    wait: yes
    groups:
      - redis
      - deltares
    region: eu-west-1
    count: 1
    vpc_subnet_id: subnet-487c983f
    assign_public_ip: yes
